#!/bin/bash
# Usage: qsub pbs-script
# Lev Lafayette, Systems Administrator, VPAC, 30 Dec 2010

# NOTE: To activate a PBS option, remove the whitespace between the '#' and 'PBS'

# To give your job a name, replace "PingTest" with an appropriate name
#PBS -N Classifier

# Establishe processors and walltime.
# #PBS -l nodes=8
#PBS -l nodes=64

#PBS -l walltime=05:00:00
# Changes directory to your execution directory. 
cd $PBS_O_WORKDIR
module load openmpi/1.6.3-gcc
# #export LD_LIBRARY_PATH=/usr/local/openmpi/1.6.3-gcc/lib:$LD_LIBRARY_PATH
# Command to run an MPI job, note we specified mpiexec so dont need to
# specify the number of processes or thier names. 

mpiexec ./classifier/classifier -C config.txt -T RealImagesWS30.csv  
