
# Will Smart  5/1/2004

vgp : ../src/allc.c ../src/allc.h ../src/node.c ../src/node.h ../src/op.c ../src/op.h ../src/rand.c ../src/rand.h ../src/main.c ../src/pop.c ../src/fit.c \
      common.h main.c fit.c pop.c
	gcc -DUse_SimpleClassify -O -o vgp ../src/allc.c ../src/node.c ../src/op.c ../src/rand.c main.c pop.c fit.c -lm

