***************
*** 50,57 ****
    ../../src/GeneticProgram.h ReturnMove.h ../../src/ReturnData.h \
    ../../src/GPConfig.h ../../src/Random.h ../../src/Crossover.h \
    ../../src/Mutation.h ../../src/Selection.h ../../src/NodeSet.h \
-   ../../src/GPConfig.h ../../src/Function.h ../../src/Terminal.h \
-   ../../src/NodeVector.h ../../src/NodeVector.cpp
  ReturnMove.o: ReturnMove.cpp ReturnMove.h ../../src/ReturnData.h
  ReturnCoord.o: ReturnCoord.cpp ReturnCoord.h ../../src/ReturnData.h
  ReturnBoolean.o: ReturnBoolean.cpp ReturnBoolean.h ../../src/ReturnData.h
--- 50,56 ----
    ../../src/GeneticProgram.h ReturnMove.h ../../src/ReturnData.h \
    ../../src/GPConfig.h ../../src/Random.h ../../src/Crossover.h \
    ../../src/Mutation.h ../../src/Selection.h ../../src/NodeSet.h \
+   ../../src/Function.h ../../src/Terminal.h
  ReturnMove.o: ReturnMove.cpp ReturnMove.h ../../src/ReturnData.h
  ReturnCoord.o: ReturnCoord.cpp ReturnCoord.h ../../src/ReturnData.h
  ReturnBoolean.o: ReturnBoolean.cpp ReturnBoolean.h ../../src/ReturnData.h
***************
*** 59,169 ****
    ../../src/ReturnData.h ReturnMove.h ../../src/ReturnData.h \
    ../../src/GPConfig.h ../../src/Random.h ../../src/Crossover.h \
    ../../src/GeneticProgram.h ../../src/Mutation.h ../../src/Selection.h \
-   ../../src/Fitness.h ../../src/NodeSet.h ../../src/GPConfig.h \
-   ../../src/Function.h ../../src/Terminal.h ../../src/NodeVector.h \
-   ../../src/NodeVector.cpp
  MoveDown.o: MoveDown.cpp MoveDown.h ../../src/Terminal.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnMove.h ../../src/ReturnData.h \
    ../../src/GPConfig.h ../../src/Random.h ../../src/Crossover.h \
    ../../src/GeneticProgram.h ../../src/Mutation.h ../../src/Selection.h \
-   ../../src/Fitness.h ../../src/NodeSet.h ../../src/GPConfig.h \
-   ../../src/Function.h ../../src/Terminal.h ../../src/NodeVector.h \
-   ../../src/NodeVector.cpp
  MoveLeft.o: MoveLeft.cpp MoveLeft.h ../../src/Terminal.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnMove.h ../../src/ReturnData.h \
    ../../src/GPConfig.h ../../src/Random.h ../../src/Crossover.h \
    ../../src/GeneticProgram.h ../../src/Mutation.h ../../src/Selection.h \
-   ../../src/Fitness.h ../../src/NodeSet.h ../../src/GPConfig.h \
-   ../../src/Function.h ../../src/Terminal.h ../../src/NodeVector.h \
-   ../../src/NodeVector.cpp
  MoveRight.o: MoveRight.cpp MoveRight.h ../../src/Terminal.h \
    ../../src/Node.h ../../src/ReturnData.h ReturnMove.h \
    ../../src/ReturnData.h ../../src/GPConfig.h ../../src/Random.h \
    ../../src/Crossover.h ../../src/GeneticProgram.h ../../src/Mutation.h \
    ../../src/Selection.h ../../src/Fitness.h ../../src/NodeSet.h \
-   ../../src/GPConfig.h ../../src/Function.h ../../src/Terminal.h \
-   ../../src/NodeVector.h ../../src/NodeVector.cpp
  GetPredX.o: GetPredX.cpp GetPredX.h ../../src/Terminal.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnCoord.h ../../src/ReturnData.h \
    PredatorPreyFitness.h ../../src/GeneticProgram.h \
    ../../src/CoEvolutionFitness.h ../../src/Fitness.h \
    ../../src/GeneticProgram.h ReturnMove.h ../../src/GPConfig.h \
    ../../src/Random.h ../../src/Crossover.h ../../src/Mutation.h \
-   ../../src/Selection.h ../../src/NodeSet.h ../../src/GPConfig.h \
-   ../../src/Function.h ../../src/Terminal.h ../../src/NodeVector.h \
-   ../../src/NodeVector.cpp
  GetPredY.o: GetPredY.cpp GetPredY.h ../../src/Terminal.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnCoord.h ../../src/ReturnData.h \
    PredatorPreyFitness.h ../../src/GeneticProgram.h \
    ../../src/CoEvolutionFitness.h ../../src/Fitness.h \
    ../../src/GeneticProgram.h ReturnMove.h ../../src/GPConfig.h \
    ../../src/Random.h ../../src/Crossover.h ../../src/Mutation.h \
-   ../../src/Selection.h ../../src/NodeSet.h ../../src/GPConfig.h \
-   ../../src/Function.h ../../src/Terminal.h ../../src/NodeVector.h \
-   ../../src/NodeVector.cpp
  GetPreyX.o: GetPreyX.cpp GetPreyX.h ../../src/Terminal.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnCoord.h ../../src/ReturnData.h \
    PredatorPreyFitness.h ../../src/GeneticProgram.h \
    ../../src/CoEvolutionFitness.h ../../src/Fitness.h \
    ../../src/GeneticProgram.h ReturnMove.h ../../src/GPConfig.h \
    ../../src/Random.h ../../src/Crossover.h ../../src/Mutation.h \
-   ../../src/Selection.h ../../src/NodeSet.h ../../src/GPConfig.h \
-   ../../src/Function.h ../../src/Terminal.h ../../src/NodeVector.h \
-   ../../src/NodeVector.cpp
  GetPreyY.o: GetPreyY.cpp GetPreyY.h ../../src/Terminal.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnCoord.h ../../src/ReturnData.h \
    PredatorPreyFitness.h ../../src/GeneticProgram.h \
    ../../src/CoEvolutionFitness.h ../../src/Fitness.h \
    ../../src/GeneticProgram.h ReturnMove.h ../../src/GPConfig.h \
    ../../src/Random.h ../../src/Crossover.h ../../src/Mutation.h \
-   ../../src/Selection.h ../../src/NodeSet.h ../../src/GPConfig.h \
-   ../../src/Function.h ../../src/Terminal.h ../../src/NodeVector.h \
-   ../../src/NodeVector.cpp
  If.o: If.cpp If.h ../../src/Function.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnMove.h ../../src/ReturnData.h \
    ReturnBoolean.h ../../src/GPConfig.h ../../src/Random.h \
    ../../src/Crossover.h ../../src/GeneticProgram.h ../../src/Mutation.h \
    ../../src/Selection.h ../../src/Fitness.h ../../src/NodeSet.h \
-   ../../src/GPConfig.h ../../src/Function.h ../../src/Terminal.h \
-   ../../src/NodeVector.h ../../src/NodeVector.cpp
  LessThan.o: LessThan.cpp LessThan.h ../../src/Function.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnCoord.h ../../src/ReturnData.h \
    ReturnBoolean.h ../../src/GPConfig.h ../../src/Random.h \
    ../../src/Crossover.h ../../src/GeneticProgram.h ../../src/Mutation.h \
    ../../src/Selection.h ../../src/Fitness.h ../../src/NodeSet.h \
-   ../../src/GPConfig.h ../../src/Function.h ../../src/Terminal.h \
-   ../../src/NodeVector.h ../../src/NodeVector.cpp
  GreaterThan.o: GreaterThan.cpp GreaterThan.h ../../src/Function.h \
    ../../src/Node.h ../../src/ReturnData.h ReturnCoord.h \
    ../../src/ReturnData.h ReturnBoolean.h ../../src/GPConfig.h \
    ../../src/Random.h ../../src/Crossover.h ../../src/GeneticProgram.h \
    ../../src/Mutation.h ../../src/Selection.h ../../src/Fitness.h \
-   ../../src/NodeSet.h ../../src/GPConfig.h ../../src/Function.h \
-   ../../src/Terminal.h ../../src/NodeVector.h ../../src/NodeVector.cpp
  And.o: And.cpp And.h ../../src/Function.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnBoolean.h ../../src/ReturnData.h \
    ../../src/GPConfig.h ../../src/Random.h ../../src/Crossover.h \
    ../../src/GeneticProgram.h ../../src/Mutation.h ../../src/Selection.h \
-   ../../src/Fitness.h ../../src/NodeSet.h ../../src/GPConfig.h \
-   ../../src/Function.h ../../src/Terminal.h ../../src/NodeVector.h \
-   ../../src/NodeVector.cpp
  Or.o: Or.cpp Or.h ../../src/Function.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnBoolean.h ../../src/ReturnData.h \
    ../../src/GPConfig.h ../../src/Random.h ../../src/Crossover.h \
    ../../src/GeneticProgram.h ../../src/Mutation.h ../../src/Selection.h \
-   ../../src/Fitness.h ../../src/NodeSet.h ../../src/GPConfig.h \
-   ../../src/Function.h ../../src/Terminal.h ../../src/NodeVector.h \
-   ../../src/NodeVector.cpp
  main.o: main.cpp ../../src/CoEvolutionPopulation.h \
    ../../src/GeneticProgram.h ../../src/ReturnData.h ../../src/Node.h \
    ../../src/Mutation.h ../../src/Crossover.h ../../src/Selection.h \
    ../../src/Population.h ../../src/GPConfig.h ../../src/Random.h \
    ../../src/Fitness.h ../../src/NodeSet.h ../../src/Function.h \
-   ../../src/Terminal.h ../../src/NodeVector.h ../../src/NodeVector.cpp \
-   PredatorPreyFitness.h ../../src/GeneticProgram.h \
    ../../src/CoEvolutionFitness.h ReturnMove.h ../../src/ReturnData.h \
-   ../../src/NodeSet.h ../../src/ProgramGenerator.h If.h \
-   ../../src/Function.h LessThan.h GreaterThan.h And.h Or.h GetPredX.h \
-   ../../src/Terminal.h GetPredY.h GetPreyX.h GetPreyY.h MoveUp.h \
-   MoveDown.h MoveLeft.h MoveRight.h ReturnCoord.h ReturnBoolean.h \
-   ../../src/GPConfig.h
--- 58,154 ----
    ../../src/ReturnData.h ReturnMove.h ../../src/ReturnData.h \
    ../../src/GPConfig.h ../../src/Random.h ../../src/Crossover.h \
    ../../src/GeneticProgram.h ../../src/Mutation.h ../../src/Selection.h \
+   ../../src/Fitness.h ../../src/NodeSet.h ../../src/Function.h \
+   ../../src/Terminal.h
  MoveDown.o: MoveDown.cpp MoveDown.h ../../src/Terminal.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnMove.h ../../src/ReturnData.h \
    ../../src/GPConfig.h ../../src/Random.h ../../src/Crossover.h \
    ../../src/GeneticProgram.h ../../src/Mutation.h ../../src/Selection.h \
+   ../../src/Fitness.h ../../src/NodeSet.h ../../src/Function.h \
+   ../../src/Terminal.h
  MoveLeft.o: MoveLeft.cpp MoveLeft.h ../../src/Terminal.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnMove.h ../../src/ReturnData.h \
    ../../src/GPConfig.h ../../src/Random.h ../../src/Crossover.h \
    ../../src/GeneticProgram.h ../../src/Mutation.h ../../src/Selection.h \
+   ../../src/Fitness.h ../../src/NodeSet.h ../../src/Function.h \
+   ../../src/Terminal.h
  MoveRight.o: MoveRight.cpp MoveRight.h ../../src/Terminal.h \
    ../../src/Node.h ../../src/ReturnData.h ReturnMove.h \
    ../../src/ReturnData.h ../../src/GPConfig.h ../../src/Random.h \
    ../../src/Crossover.h ../../src/GeneticProgram.h ../../src/Mutation.h \
    ../../src/Selection.h ../../src/Fitness.h ../../src/NodeSet.h \
+   ../../src/Function.h ../../src/Terminal.h
  GetPredX.o: GetPredX.cpp GetPredX.h ../../src/Terminal.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnCoord.h ../../src/ReturnData.h \
    PredatorPreyFitness.h ../../src/GeneticProgram.h \
    ../../src/CoEvolutionFitness.h ../../src/Fitness.h \
    ../../src/GeneticProgram.h ReturnMove.h ../../src/GPConfig.h \
    ../../src/Random.h ../../src/Crossover.h ../../src/Mutation.h \
+   ../../src/Selection.h ../../src/NodeSet.h ../../src/Function.h \
+   ../../src/Terminal.h
  GetPredY.o: GetPredY.cpp GetPredY.h ../../src/Terminal.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnCoord.h ../../src/ReturnData.h \
    PredatorPreyFitness.h ../../src/GeneticProgram.h \
    ../../src/CoEvolutionFitness.h ../../src/Fitness.h \
    ../../src/GeneticProgram.h ReturnMove.h ../../src/GPConfig.h \
    ../../src/Random.h ../../src/Crossover.h ../../src/Mutation.h \
+   ../../src/Selection.h ../../src/NodeSet.h ../../src/Function.h \
+   ../../src/Terminal.h
  GetPreyX.o: GetPreyX.cpp GetPreyX.h ../../src/Terminal.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnCoord.h ../../src/ReturnData.h \
    PredatorPreyFitness.h ../../src/GeneticProgram.h \
    ../../src/CoEvolutionFitness.h ../../src/Fitness.h \
    ../../src/GeneticProgram.h ReturnMove.h ../../src/GPConfig.h \
    ../../src/Random.h ../../src/Crossover.h ../../src/Mutation.h \
+   ../../src/Selection.h ../../src/NodeSet.h ../../src/Function.h \
+   ../../src/Terminal.h
  GetPreyY.o: GetPreyY.cpp GetPreyY.h ../../src/Terminal.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnCoord.h ../../src/ReturnData.h \
    PredatorPreyFitness.h ../../src/GeneticProgram.h \
    ../../src/CoEvolutionFitness.h ../../src/Fitness.h \
    ../../src/GeneticProgram.h ReturnMove.h ../../src/GPConfig.h \
    ../../src/Random.h ../../src/Crossover.h ../../src/Mutation.h \
+   ../../src/Selection.h ../../src/NodeSet.h ../../src/Function.h \
+   ../../src/Terminal.h
  If.o: If.cpp If.h ../../src/Function.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnMove.h ../../src/ReturnData.h \
    ReturnBoolean.h ../../src/GPConfig.h ../../src/Random.h \
    ../../src/Crossover.h ../../src/GeneticProgram.h ../../src/Mutation.h \
    ../../src/Selection.h ../../src/Fitness.h ../../src/NodeSet.h \
+   ../../src/Function.h ../../src/Terminal.h
  LessThan.o: LessThan.cpp LessThan.h ../../src/Function.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnCoord.h ../../src/ReturnData.h \
    ReturnBoolean.h ../../src/GPConfig.h ../../src/Random.h \
    ../../src/Crossover.h ../../src/GeneticProgram.h ../../src/Mutation.h \
    ../../src/Selection.h ../../src/Fitness.h ../../src/NodeSet.h \
+   ../../src/Function.h ../../src/Terminal.h
  GreaterThan.o: GreaterThan.cpp GreaterThan.h ../../src/Function.h \
    ../../src/Node.h ../../src/ReturnData.h ReturnCoord.h \
    ../../src/ReturnData.h ReturnBoolean.h ../../src/GPConfig.h \
    ../../src/Random.h ../../src/Crossover.h ../../src/GeneticProgram.h \
    ../../src/Mutation.h ../../src/Selection.h ../../src/Fitness.h \
+   ../../src/NodeSet.h ../../src/Function.h ../../src/Terminal.h
  And.o: And.cpp And.h ../../src/Function.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnBoolean.h ../../src/ReturnData.h \
    ../../src/GPConfig.h ../../src/Random.h ../../src/Crossover.h \
    ../../src/GeneticProgram.h ../../src/Mutation.h ../../src/Selection.h \
+   ../../src/Fitness.h ../../src/NodeSet.h ../../src/Function.h \
+   ../../src/Terminal.h
  Or.o: Or.cpp Or.h ../../src/Function.h ../../src/Node.h \
    ../../src/ReturnData.h ReturnBoolean.h ../../src/ReturnData.h \
    ../../src/GPConfig.h ../../src/Random.h ../../src/Crossover.h \
    ../../src/GeneticProgram.h ../../src/Mutation.h ../../src/Selection.h \
+   ../../src/Fitness.h ../../src/NodeSet.h ../../src/Function.h \
+   ../../src/Terminal.h
  main.o: main.cpp ../../src/CoEvolutionPopulation.h \
    ../../src/GeneticProgram.h ../../src/ReturnData.h ../../src/Node.h \
    ../../src/Mutation.h ../../src/Crossover.h ../../src/Selection.h \
    ../../src/Population.h ../../src/GPConfig.h ../../src/Random.h \
    ../../src/Fitness.h ../../src/NodeSet.h ../../src/Function.h \
+   ../../src/Terminal.h PredatorPreyFitness.h ../../src/GeneticProgram.h \
    ../../src/CoEvolutionFitness.h ReturnMove.h ../../src/ReturnData.h \
+   ../../src/NodeSet.h ../../src/ProgramGenerator.h ../../src/NodeVector.h \
+   If.h ../../src/Function.h LessThan.h GreaterThan.h And.h Or.h \
+   GetPredX.h ../../src/Terminal.h GetPredY.h GetPreyX.h GetPreyY.h \
+   MoveUp.h MoveDown.h MoveLeft.h MoveRight.h ReturnCoord.h \
+   ReturnBoolean.h ../../src/GPConfig.h
